service: serverless-next

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

package:
  include:
    - dist/
    - src/pages/
    - next.config.js

functions:
  app:
    handler: dist/lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
